// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  centered_description: dynamic(() => import("./CenteredDescription")),
  contact_form: dynamic(() => import("./ContactForm")),
  heading_list: dynamic(() => import("./HeadingList")),
  headline: dynamic(() => import("./Headline")),
  hero_content_centered: dynamic(() => import("./HeroContentCentered")),
  highlighted_heading: dynamic(() => import("./HighlightedHeading")),
  media_cta_with_featured_content: dynamic(
    () => import("./MediaCtaWithFeaturedContent"),
  ),
  personal_message: dynamic(() => import("./PersonalMessage")),
  split_text_media: dynamic(() => import("./SplitTextMedia")),
  stacked_headings: dynamic(() => import("./StackedHeadings")),
  text: dynamic(() => import("./Text")),
  work_highlights_grid: dynamic(() => import("./WorkHighlightsGrid")),
};
